apiVersion: 1

datasources:
  - name: Metrics
    uid: Metrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "30s"

  - name: Logging
    uid: Logging
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: Tracing
    uid: Tracing
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogs:
        datasourceUid: 'Logging'
        spanStartTimeShift: '-1s'
        spanEndTimeShift: '2s'
        filterByTraceID: true
        filterBySpanID: true
      tracesToMetrics:
        datasourceUid: 'Metrics'
      serviceMap:
        datasourceUid: 'Metrics'
