.build:{{ app_name }}:
  image:
    name: martizih/kaniko:v1.25.3-debug
    entrypoint: [""]
  interruptible: true
  tags:
    - linux
    - project
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/apps/{{ app_name }}/Dockerfile --destination $ECR_HOST/$REPOSITORY_NAME:$TAGGING-{{ app_name }} --snapshot-mode=redo --compression-level=4

build:development-docker:
  stage: build:development
  interruptible: true
  tags:
    - linux
    - project
  extends:
    - .build:{{ app_name }}
    - .rules:development
  variables:
    TAGGING: $CI_COMMIT_SHORT_SHA
  environment:
    name: 'development'
    action: 'prepare'

build:staging-docker:
  stage: build:staging
  interruptible: true
  tags:
    - linux
    - project
  extends:
    - .build:{{ app_name }}
    - .rules:development
  variables:
    TAGGING: $CI_COMMIT_REF_NAME
  environment:
    name: 'development'
    action: 'prepare'

build:production-docker:
  stage: build:production
  interruptible: true
  tags:
    - linux
    - project
  extends:
    - .build:{{ app_name }}
    - .rules:development
  variables:
    TAGGING: $CI_COMMIT_REF_NAME
  environment:
    name: 'development'
    action: 'prepare'


