-- Translated verbatim from the original alembic migration:
-- apps/fastapi-ai/app/database/migration/versions/989eb3ef44de_create_users_table.py
--
-- Schema preserved exactly: column order, types, nullability, defaults,
-- uniqueness, and all three indexes (including the non-unique ix_users_id
-- which alembic emits automatically from the SQLAlchemy `index=True`
-- on the primary-key column).

CREATE TABLE IF NOT EXISTS users (
    id             INTEGER                  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name      VARCHAR                  NOT NULL,
    username       VARCHAR                  NOT NULL,
    phone_number   VARCHAR                  NOT NULL,
    email          VARCHAR                  NOT NULL,
    password_hash  VARCHAR                  NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at     TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email    ON users (email);
CREATE UNIQUE INDEX IF NOT EXISTS ix_users_username ON users (username);
CREATE        INDEX IF NOT EXISTS ix_users_id       ON users (id);
