{
 "title": "Enhanced Nginx Load Balancer Dashboard",
 "description": "Enhanced Nginx Load Balancer Dashboard using JSON access logs with Loki v2+",
 "tags": [
  "loki",
  "nginx",
  "load-balancer",
  "enhanced"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({job=~\"$job\"}, host)"
   }
  ]
 },
 "panels": [
  { "title": "KPI's", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# NGINX log lines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=~\"$job\", host=~\"$host\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=~\"$job\", host=~\"$host\"} | json | __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {% raw %}{{status}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({job=~\"$job\", host=~\"$host\"} | json | unwrap body_bytes_sent | __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Realtime visitors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({job=~\"$job\", host=~\"$host\"} | json | __error__=\"\" [$__interval])))"
    }
   ]
  },
  {
   "title": "% 5xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\", host=~\"$host\"} | json | status >= 500 | __error__=\"\"[$__interval])) / (sum(count_over_time({job=~\"$job\", host=~\"$host\"} | json | __error__=\"\"[$__interval]))/ 100)"
    }
   ]
  },
  {
   "title": "Upstream Avg",
   "type": "stat",
   "description": "Average upstream response time in milliseconds",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time({job=~\"$job\", host=~\"$host\"} | json | unwrap upstream_response_time | __error__=\"\" [5m])) * 1000"
    }
   ]
  },
  {
   "title": "NGINX logs in bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "bytes_over_time({job=~\"$job\", host=~\"$host\"}[$__interval])",
     "legendFormat": "$host"
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"$job\", host=~\"$host\"} | json | line_format \"[{% raw %}{{.geoip_country_code}}{% endraw %}] {% raw %}{{.remote_addr}}{% endraw %} {% raw %}{{.request_method}}{% endraw %} {% raw %}{{.request_uri}}{% endraw %} {% raw %}{{.status}}{% endraw %} ({% raw %}{{.body_bytes_sent}}{% endraw %}B) {% raw %}{{.request_time}}{% endraw %}s\"",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({job=~\"$job\", host=~\"$host\"}[$__interval]))  "
    }
   ]
  },
  {
   "title": "Requests per Country",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (geoip_country_code) (count_over_time({job=~\"$job\", host=~\"$host\"} | json | geoip_country_code != \"\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{% raw %}{{geoip_country_code}}{% endraw %}"
    }
   ]
  },
  { "title": "Request statistics over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Response Time Analysis",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{job=~\"$job\", host=~\"$host\"} | json | unwrap request_time | __error__=\"\"  [$__interval]) by (host)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "quantile_over_time(0.95,{job=~\"$job\", host=~\"$host\"} | json | unwrap upstream_response_time | __error__=\"\"  [$__interval]) by (host)",
     "legendFormat": "upstream 95th"
    },
    {
     "expr": "avg_over_time({job=~\"$job\", host=~\"$host\"} | json | unwrap request_time | __error__=\"\"  [$__interval]) by (host)",
     "legendFormat": "total avg"
    }
   ]
  },
  {
   "title": "HTTP status codes over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=~\"$job\", host=~\"$host\"} | json | __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status {% raw %}{{status}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Request Rate/s",
   "type": "timeseries",
   "description": "Requests per second rate based on log count",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\", host=~\"$host\"} | json | __error__=\"\" [$__interval])) / 60",
     "legendFormat": "Request Rate"
    }
   ]
  }
 ]
}