import { isCI } from 'std-env'
import { defineConfig } from 'vitest/config'

export default defineConfig({
  resolve: { tsconfigPaths: true },
  test: {
    environment: 'happy-dom',
    exclude: ['node_modules', 'tests-e2e'],
    // junit is what GitLab/GitHub test-report widgets consume; github-actions annotates PRs.
    reporters: isCI ? ['default', 'junit', 'github-actions'] : ['html', 'default'],
    include: ['./tests/**/*.{test,spec}.{ts,tsx}'],
    setupFiles: ['./tests/setup-client.ts'],
    outputFile: {
      json: './tests-results/vitest-results.json',
      junit: './tests-results/junit.xml',
      html: './tests-results/index.html',
    },
    coverage: {
      provider: 'v8',
      reporter: ['html-spa', 'text-summary'],
      reportsDirectory: './tests-results/coverage',
      cleanOnRerun: true,
      clean: true,
      // Count every source file, not only the ones a test happened to import;
      // otherwise an untested module silently does not lower the number.
      include: ['app/**/*.{ts,tsx}'],
      exclude: [
        'app/routeTree.gen.ts', // generated by `tsr generate`
        'app/main.tsx', // browser bootstrap
        'app/router.tsx', // router instance, exercised via routeTree in tests
        '**/*.css.ts', // style objects
        '**/*.d.ts',
      ],
      // Floors are a project decision, so none ship with the template. Once you have a
      // baseline, set each to (measured - 5) and only ever raise them, e.g.:
      //   thresholds: { lines: 80, branches: 80, perFile: false },
    },
    globals: true,
  },
})
