.build:apps:
  image:
    name: quay.io/buildah/stable:v1.40.1
  interruptible: true
  tags:
    - linux
    - project
  before_script:
    - |
      cat > /etc/containers/registries.conf <<EOF
      [registries.search]
      registries = ['docker.io']

      [registries.insecure]
      registries = []

      [registries.block]
      registries = []
      EOF
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - sudo yum install unzip -y
    - unzip awscliv2.zip
    - sudo ./aws/install
  script:
    - aws ecr get-login-password --region ap-southeast-1 | buildah login --username AWS --password-stdin <AWS_ACCOUNT_NUMBER>.dkr.ecr.ap-southeast-1.amazonaws.com
    - buildah build --isolation=chroot -f $CI_PROJECT_DIR/apps/api/Dockerfile --layers --cache-to $ECR_HOST/$REPOSITORY_NAME --layers --cache-from $ECR_HOST/$REPOSITORY_NAME -t $ECR_HOST/$REPOSITORY_NAME:$TAGGING $CI_PROJECT_DIR/apps/api
    - buildah push $ECR_HOST/$REPOSITORY_NAME:$TAGGING

build:development-docker:
  stage: build:development
  interruptible: true
  tags:
    - linux
    - project
  extends:
    - .build:apps
    - .rules:development
  variables:
    TAGGING: $CI_COMMIT_SHORT_SHA
  environment:
    name: 'development'
    action: 'prepare'

build:staging-docker:
  stage: build:staging
  interruptible: true
  tags:
    - linux
    - project
  extends:
    - .build:apps
    - .rules:development
  variables:
    TAGGING: $CI_COMMIT_REF_NAME
  environment:
    name: 'development'
    action: 'prepare'

build:production-docker:
  stage: build:production
  interruptible: true
  tags:
    - linux
    - project
  extends:
    - .build:apps
    - .rules:development
  variables:
    TAGGING: $CI_COMMIT_REF_NAME
  environment:
    name: 'development'
    action: 'prepare'


