stages:
  - test
  - build:development
  - deploy:development
  - build:staging
  - deploy:staging
  - build:production
  - deploy:production

include:
  - /deploy/pipelines/dependencies/main.yml
  - /deploy/pipelines/test/test.yml
  - /deploy/pipelines/app/main.yml
