$schema: https://moonrepo.dev/schemas/v2/project.json
toolchains:
  default: system
language: unknown
project:
  description: '{{ package_description }}'
  title: '{{ package_name | kebab_case }}'
stack: infrastructure
tags:
- config
id: '{{ package_name | kebab_case }}'
layer: configuration
