# https://moonrepo.dev/docs/config/template
# yaml-language-server: $schema=https://moonrepo.dev/schemas/template.json
$schema: 'https://moonrepo.dev/schemas/template.json'

# REQUIRED: Name of the template in a human readable format.
title: 'Gitlab'

# REQUIRED: Description of what the template is for and other relevant information.
description: 'Gitlab CI/CD'

# Destination path for the package.
destination: 'infra/[package_name]'

# Mapping of variables that will be interpolated and rendered within template files.
# Users will be prompted to provide a value when running the generator.
variables:
  package_name:
    type: 'string'
    default: 'gitlab'
    prompt: 'Package name (identifier)?'
    required: true

  package_description:
    type: 'string'
    default: 'Gitlab CI/CD'
    prompt: 'Package description?'
    required: true

  aws_account_number:
    type: 'number'
    default: 111111111111
    prompt: 'AWS account number at least 12 digits number (you can change it later)?'
    required: false

  app_name:
    type: 'string'
    default: 'CHANGEME_APP_NAME'
    prompt: 'App name will use on build for app name and deploy for folder sync name, It depend on package name on what app you generate for example if you generate template-react-app then the value will react-app (you can change it later)?'
    required: false

  region:
    type: 'string'
    default: 'CHANGEME_AWS_REGION'
    prompt: 'AWS region (you can change it later)?'
    required: false

  mobile_app_name:
    type: 'string'
    default: 'CHANGEME_MOBILE_APP_NAMES'
    prompt: 'Mobile apps name on deploy.yml for mobile ci/cd (you can change it later)?'
    required: false

