# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

# Mailpit is an email and SMTP testing tool with API for developers.
# @see: https://mailpit.axllent.org/docs/configuration
services:
  mailpit:
    image: axllent/mailpit:latest
    # restart: unless-stopped
    volumes:
      - mailpit_data:/data
    ports:
      - 1025:1025 # port the SMTP server should be accessible on
      - 8025:8025 # port the web interface should be accessible on
    environment:
      # https://github.com/axllent/mailpit/wiki/Runtime-options
      # MP_UI_AUTH: 'user1:password1 user2:password2'
      TZ: Asia/Jakarta

volumes:
  mailpit_data:
    driver: local
