services:
  redis:
    image: redis:8.0.2-alpine3.21
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
    networks:
      - overlay-network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    configs:
      - source: redis_conf
        target: /usr/local/etc/redis/redis.conf

configs:
  redis_conf:
    file: ./redis.conf

volumes:
  redis_data:
    name: redis_data

networks:
  overlay-network:
    external: true
