// Package models contains HTTP request/response schema definitions for the user module.
// This file defines struct types used for HTTP payloads, validation, and OpenAPI documentation.

package models

type UserCreateRequest struct {
	Name     string `json:"name" validate:"required" example:"John Doe"`
	Email    string `json:"email" validate:"required,email" example:"johndoe@example.com"`
	Password string `json:"password" validate:"required,min=8" example:"secure.password"`
	Username string `json:"-" example:"johndoe"` // username generated by system, not visible to the user
}
