//! User model.
//!
//! Mirrors `app/model/user.py::User` AND the full shape of the actual
//! alembic migration (not just the shortened `SQLAlchemy` class — the
//! migration adds `created_at` and `updated_at` timestamp columns that
//! the Python class doesn't declare but that live in the database).
//!
//! Schema (verified against
//! `apps/fastapi-ai/app/database/migration/versions/989eb3ef44de_create_users_table.py`
//! and the running `rust_ai` database):
//!
//! ```sql
//! CREATE TABLE users (
//!     id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
//!     full_name     VARCHAR NOT NULL,
//!     username      VARCHAR NOT NULL,
//!     phone_number  VARCHAR NOT NULL,
//!     email         VARCHAR NOT NULL,
//!     password_hash VARCHAR NOT NULL,
//!     created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
//!     updated_at    TIMESTAMPTZ
//! );
//! CREATE UNIQUE INDEX ix_users_email    ON users (email);
//! CREATE UNIQUE INDEX ix_users_username ON users (username);
//! CREATE        INDEX ix_users_id       ON users (id);
//! ```

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct User {
    pub id: i32,
    pub full_name: String,
    pub username: String,
    pub phone_number: String,
    pub email: String,
    pub password_hash: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: Option<DateTime<Utc>>,
}
