//! Auth domain types. Mirrors `apps/{{ package_name | kebab_case }}/domain/auth.go`.

use serde::{Deserialize, Serialize};

use crate::domain::user::User;

#[derive(Debug, Clone, Deserialize)]
pub struct LoginRequest {
    pub email: String,
    pub password: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct LoginResponse {
    pub user: User,
    pub token: String,
    pub refresh_token: String,
}

/// JWT claim structure matching the Go `domain.JwtClaim` shape.
///
/// The Go code embeds `jwt.RegisteredClaims` which serializes its
/// fields inline (e.g., `exp`, `iat`). We replicate that flat shape
/// with explicit serde field names so tokens generated by the Rust
/// port decode identically in Go's jwt/v5 and vice versa.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JwtClaim {
    pub id: String,
    pub email: String,
    #[serde(rename = "exp")]
    pub exp: i64,
    #[serde(rename = "iat")]
    pub iat: i64,
}
