apiVersion: 1
templates:
  - orgId: 1
    name: slack.custom.title
    template: |
      {% raw %}
      {{ define "slack.custom.title" }}
      {{ range $i, $alert := .Alerts }}
        {{ if $i }}, {{ end }}
        {{ if eq $alert.Status "firing" }}🚨 [FIRING]{{ else if eq $alert.Status "resolved" }}✅ [RESOLVED]{{ end }} {{ $alert.Labels.alertname }}
      {{ end }}
      {{ end }}
      {% endraw %}

  - orgId: 1
    name: slack.custom.message
    template: |
      {% raw %}
      {{ define "slack.custom.message" }}
      {{ range $index, $alert := .Alerts -}}
      >*Status:* {{ $alert.Status | title }}
      {{- if eq $alert.Status "firing" }}
        {{- if $alert.Annotations.summary_firing }}
      >*Summary:* {{ $alert.Annotations.summary_firing }}
        {{- else if $alert.Annotations.summary }}
      >*Summary:* {{ $alert.Annotations.summary }}
        {{- end }}
      {{- else if eq $alert.Status "resolved" }}
        {{- if $alert.Annotations.summary_resolved }}
      >*Summary:* {{ $alert.Annotations.summary_resolved }}
        {{- else if $alert.Annotations.summary }}
      >*Summary:* {{ $alert.Annotations.summary }}
        {{- end }}
      {{- end }}
      {{- if $alert.Labels.instance }}
      >*Instance:* `{{ $alert.Labels.instance }}`
      {{- end }}
      >🔗 <{{ $alert.GeneratorURL }}|View in Grafana>
      {{- if $alert.Annotations.description }}
      >*Description:* {{ $alert.Annotations.description }}
      {{- end }}

      {{ end -}}
      {{ end }}
      {% endraw %}
