auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info
  grpc_server_max_recv_msg_size: 1.048576e+08
  grpc_server_max_send_msg_size: 1.048576e+08
  http_server_read_timeout: 600s

common:
  path_prefix: /loki
  storage:
    s3:
      region: ap-southeast-1
      bucketnames: lgtm-buckets-monitoring
      s3forcepathstyle: false
      insecure: false
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

frontend:
  address: 0.0.0.0
  compress_responses: true

# Add query caching for better performance
query_range:
  cache_results: true
  results_cache:
    cache:
      memcached_client:
        consistent_hash: true
        addresses: memcached-loki:11211
        max_idle_conns: 16
        timeout: 500ms
        update_interval: 1m

chunk_store_config:
  chunk_cache_config:
    memcached:
      batch_size: 256
      parallelism: 10
    memcached_client:
      addresses: memcached-loki:11211

schema_config:
  configs:
    - from: 2023-07-20
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
  aws:
    region: ap-southeast-1
    bucketnames: lgtm-buckets-monitoring
    s3forcepathstyle: false
    insecure: false

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
    final_sleep: 0s
  # Better chunk settings
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  flush_check_period: 30s

compactor:
  working_directory: /loki/compactor
  retention_enabled: true
  compaction_interval: 2h
  delete_request_store: s3

limits_config:
  ingestion_rate_mb: 20
  ingestion_burst_size_mb: 40
  max_streams_per_user: 50000
  max_line_size: 256000
  max_query_parallelism: 16
  retention_period: 7d
  split_queries_by_interval: 30m
  max_concurrent_tail_requests: 10
  volume_enabled: true
