.common-ifs:
  on-merge-requests: &on-mr
    if: $CI_PIPELINE_SOURCE == "merge_request_event"

  on-merge-requests-manual: &on-mr-manual
    if: $CI_PIPELINE_SOURCE == "merge_request_event"
    when: manual

  is-schedule: &on-schedule
    if: $CI_PIPELINE_SOURCE == 'schedule'

  on-main: &on-main
    if: $CI_COMMIT_BRANCH == "main"

  on-main-manual: &on-main-manual
    if: $CI_COMMIT_BRANCH == "main"
    when: manual

  on-api-staging-tag: &on-api-staging
    if: $CI_COMMIT_TAG =~ /^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)-api-staging$/

  on-api-prod-tag: &on-api-prod
    if: $CI_COMMIT_TAG =~ /^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)-api-prod$/

  on-mobile-staging-tag: &on-mobile-staging
    if: $CI_COMMIT_TAG =~ /^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)-mobile-staging$/

  on-mobile-prod-tag: &on-mobile-prod
    if: $CI_COMMIT_TAG =~ /^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)-mobile-prod$/

.common-rules:
  never: &never
    when: never
  no-schedule:
    - <<: *on-schedule
    - <<: *never

.rules:merge-request:
  rules:
    - <<: *on-schedule
    - <<: *on-mr

.rules:development-api:
  rules:
    - <<: *on-schedule
    - <<: *on-main
      changes:
        - apps/api/**/*

.rules:development-api-seed:
  rules:
    - <<: *on-schedule
    - <<: *on-main-manual
      changes:
        - apps/api/**/*

.rules:development-mobile:
  rules:
    - <<: *on-schedule
    - <<: *on-main
      changes:
        - apps/mobile/**/*

.rules:development-infra:
  rules:
    - <<: *on-schedule
    - <<: *on-main
      changes:
          - .gitlab-ci.yml
          - infra/pipelines/**/*
          - infra/swarm/**/*

.rules:api-staging:
  rules:
    - <<: *on-api-staging

.rules:api-prod:
  rules:
    - <<: *on-api-prod

.rules:mobile-staging:
  rules:
    - <<: *on-mobile-staging

.rules:mobile-production:
  rules:
    - <<: *on-mobile-prod
