.common-ifs:
  on-merge-requests: &on-mr
    if: $CI_PIPELINE_SOURCE == "merge_request_event"
  is-schedule: &on-schedule
    if: $CI_PIPELINE_SOURCE == 'schedule'
  on-main: &on-main
    if: $CI_COMMIT_BRANCH == "main"
  on-staging-tag: &on-staging
    if: $CI_COMMIT_TAG =~ /^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)-staging$/
  on-prod-tag: &on-prod
    if: $CI_COMMIT_TAG =~ /^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)-prod$/

.common-rules:
  never: &never
    when: never
  no-schedule:
    - <<: *on-schedule
      <<: *never
  on-manual: &on-manual
    when: manual

.rules:merge-request:
  rules:
    - <<: *on-schedule
    - <<: *on-mr

.rules:development:
  rules:
    - <<: *on-schedule
    - <<: *on-main

.rules:staging:
  rules:
    - <<: *on-staging

.rules:production:
  rules:
    - <<: *on-prod
