# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

# ALLOW_EMPTY_PASSWORD is recommended only for development.
# For better performance, consider `host` mode instead `port` to avoid docker NAT.
# Notice: Docker `host` mode is NOT currently supported in Swarm Mode.
# @ref: https://docs.docker.com/reference/compose-file/networks/

services:
  redis:
    image: redis:${REDIS_VERSION:-8-alpine}
    hostname: redis
    restart: unless-stopped
    ports: ['6379:6379']
    volumes: ['redis_data:/data:rw']
    environment:
      ALLOW_EMPTY_PASSWORD: 'no'
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
    command: '--appendonly yes --appendfsync everysec --requirepass securedb'
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli --no-auth-warning -a securedb ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 5
    ulimits:
      memlock: -1
      nofile:
        soft: 262144
        hard: 262144
    shm_size: 128m # set shared memory limit
    mem_limit: 256m # set memory limit
    cpus: 1.0 # set CPUs limit
    extra_hosts: ['host.docker.internal:host-gateway']
    networks: ['myorg_network']

volumes:
  redis_data:
    driver: local
